PillowMarket/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main),
    path('products/', mainapp.products),
    path('contact/', mainapp.contact),
    path('admin/', admin.site.urls),

]

adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.admin, name='admin'),

    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users_read, name='users_read'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users_read'),
    # path('users/read/page/<page>/', adminapp.users_read, name='users_read_page'),
    path('users/read/page/<page>/', adminapp.UsersListView.as_view(), name='users_read_page'),
    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('product/create/ofcategory/<int:pk>/', adminapp.ProductCreateOfCategoryView.as_view(), name='product_create_ofcategory'),
    path('product/create/oftype/<int:pk>/', adminapp.ProductCreateOfTypeView.as_view(), name='product_create_oftype'),
    # path('products/read/category/<int:pk>/', adminapp.products_category_read, name='products_category_read'),
    path('products/read/category/<int:pk>/', adminapp.ProductsCategoryListView.as_view(), name='products_category_read'),
    # path('products/read/category/<int:pk>/page/<page>/', adminapp.products_category_read, name='products_category_read_page'),
    path('products/read/category/<int:pk>/page/<page>/', adminapp.ProductsCategoryListView.as_view(), name='products_category_read_page'),
    # path('products/read/type/<int:pk>/', adminapp.products_type_read, name='products_type_read'),
    path('products/read/type/<int:pk>/', adminapp.ProductsTypeListView.as_view(), name='products_type_read'),
    # path('products/read/type/<int:pk>/page/<page>/', adminapp.products_type_read, name='products_type_read_read_page'),
    path('products/read/type/<int:pk>/page/<page>/', adminapp.ProductsTypeListView.as_view(), name='products_type_read_page'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    # path('products/delete/ct/<int:pk_category>/<int:pk>/', adminapp.product_ct_delete, name='product_ct_delete'),
    path('products/delete/ct/<int:pk>/', adminapp.ProductOfCategoryDeleteView.as_view(), name='product_ct_delete'),
    # path('products/delete/tp/<int:pk_type>/<int:pk>/', adminapp.product_tp_delete, name='product_tp_delete'),
    path('products/delete/tp/<int:pk>/', adminapp.ProductOfTypeDeleteView.as_view(), name='product_tp_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.CategoriesReadListView.as_view(), name='categories_read'),
    path('categories/read/page/<page>/', adminapp.CategoriesReadListView.as_view(), name='categories_read_page'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('types/create/', adminapp.TypeCreateView.as_view(), name='type_create'),
    # path('types/read/', adminapp.types_read, name='types_read'),
    path('types/read/', adminapp.TypesReadListView.as_view(), name='types_read'),
    # path('types/read/page/<page>/', adminapp.types_read, name='types_read_page'),
    path('types/read/page/<page>/', adminapp.TypesReadListView.as_view(), name='types_read_page'),
    path('types/update/<int:pk>/', adminapp.TypeUpdateView.as_view(), name='type_update'),
    path('types/delete/<int:pk>/', adminapp.TypeDeleteView.as_view(), name='type_delete'),

]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('registry/', authapp.registry, name='registry'),
    path('edit/', authapp.edit, name='edit'),
    path('verification/<email>/<activation_key>/', authapp.verification, name='verification')

]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('page/<page>/', mainapp.products, name='index_page'),

   path('<int:pk_cat>/', mainapp.products, name='pr_category'),
   path('<int:pk_cat>/page/<page>/', mainapp.products, name='pr_category_page'),

   # path('<int:pk_type>/', mainapp.products, name='pr_type'),

   path('single_product/<int:pk>/', mainapp.SingleProductDetailView.as_view(), name='single_product'),
]

pillowmarket/urls.py
# from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/forms.py
from django import forms

from authapp.forms import BuyerEditForm
from authapp.models import Buyer
from mainapp.models import ProductCategory, ProductType, Product


class AdminEditFormBuyer(BuyerEditForm):
    class Meta:
        model = Buyer
        fields = '__all__'


class AdminEditFormProductCategory(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AdminEditFormProductCategory, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class AdminEditFormProductType(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AdminEditFormProductType, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class AdminEditFormProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AdminEditFormProduct, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from adminapp.forms import AdminEditFormProductCategory, AdminEditFormProductType, \
    AdminEditFormProduct, AdminEditFormBuyer
from authapp.forms import BuyerRegistyForm
from authapp.models import Buyer
from mainapp.models import ProductCategory, ProductType, Product


@user_passes_test(lambda x: x.is_superuser)
def admin(request):
    title = 'adm/ Админка'
    content = {
        'title': title,
    }
    return render(request, 'adminapp/admin.html', content)


# def get_paginator_page(_objs, _page):
#     _paginator = Paginator(_objs, 2)
#     try:  # вывести страницу продуктов номер page
#         _objs_paginator = _paginator.page(_page)
#     except PageNotAnInteger:  # если страница не целое число, то вывести первую
#         _objs_paginator = _paginator.page(1)
#     except EmptyPage:  # если больше максимальной, то последнюю
#         _objs_paginator = _paginator.page(_paginator.num_pages)
#     return _objs_paginator


# users =============== users =============== users =============== users =============== users
class UsersListView(ListView):
    model = Buyer
    template_name = 'adminapp/users.html'  # в шаблон теперь передаётся object_list

    # переопределяем встроенный метод, накладываем декоратор
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    # добавляем данные в контекст
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Пользователи'
        return context_data

    # пагинатор, указвываем колю-во на странице, на страницу передаётся page_obj
    paginate_by = 3


# @user_passes_test(lambda x: x.is_superuser)
# def users_read(request, page=1):
#     title = 'adm/пользователи'
#     users_list = Buyer.objects.all().order_by('-is_active', '-is_superuser', 'username', 'first_name', 'last_name')
#     users_list_paginator = get_paginator_page(users_list, page)
#     content = {
#         'title': title,
#         'objects': users_list_paginator
#     }
#     return render(request, 'adminapp/users.html', content)

class UserCreateView(CreateView):
    model = Buyer
    template_name = 'adminapp/user.html'
    success_url = reverse_lazy('admin:users_read')
    form_class = BuyerRegistyForm

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создать пользователя'
        return context_data


# @user_passes_test(lambda x: x.is_superuser)
# def user_create(request):
#     title = 'adm/Новый пользователь'
#     if request.method == 'POST':
#         user_form = BuyerRegistyForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin:users_read'))
#     else:
#         user_form = BuyerRegistyForm()
#     content = {
#         'title': title,
#         'objects': user_form
#     }
#     return render(request, 'adminapp/user.html', content)


class UserUpdateView(UpdateView):
    model = Buyer
    template_name = 'adminapp/user.html'
    success_url = reverse_lazy('admin:users_read')
    form_class = AdminEditFormBuyer

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Просмотр/Редактирование пользователя'
        return context_data


# @user_passes_test(lambda x: x.is_superuser)
# def user_update(request, pk):
#     title = 'adm/Редактирование пользователя'
#     user = get_object_or_404(Buyer, pk=pk)
#
#     if request.method == 'POST':
#         user_form = AdminEditFormBuyer(request.POST, request.FILES, instance=user)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin:user_update', args=[user.pk]))
#     else:
#         user_form = AdminEditFormBuyer(instance=user)
#     content = {
#         'title': title,
#         'objects': user_form,
#     }
#     return render(request, 'adminapp/user.html', content)


class UserDeleteView(DeleteView):
    model = Buyer
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin:users_read')
    form_class = AdminEditFormBuyer

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление пользователя'
        return context_data

    # переопределяем метод удаления (на is_active)
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda x: x.is_superuser)
# def user_delete(request, pk):
#     title = 'adm/Удаление пользователя'
#     user = get_object_or_404(Buyer, pk=pk)
#     if user.is_active is True:
#         if request.method == 'POST':
#             user.is_active = False
#             user.save()
#             return HttpResponseRedirect(reverse('admin:users_read'))
#         content = {
#             'title': title,
#             'object_del': user
#         }
#         return render(request, 'adminapp/user_delete.html', content)
#     else:
#         # if request.method == 'POST':
#         user.is_active = True
#         user.save()
#         return HttpResponseRedirect(reverse('admin:users_read'))


# products =============== products =============== products =============== products
# просмотр совмещён с редактированием, сделать отдельно
# class ProductsCategoryDetailView(DetailView):
#     model = Product
#     template_name = 'adminapp/product.html'
#
#     @method_decorator(user_passes_test(lambda x: x.is_superuser))
#     def dispatch(self, *args, **kwargs):
#         return super().dispatch(*args, **kwargs)
#
#     def get_context_data(self, **kwargs):
#         context_data = super().get_context_data(**kwargs)
#         context_data['from_category'] = True
#         return context_data

class ProductsCategoryListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 3

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'товары данной категории'
        context_data['objects_of_category'] = True  # для выбора нужного цикла в шаблоне
        context_data['objects_of_type'] = False  # для выбора нужного цикла в шаблоне
        context_data['pk_category'] = self.kwargs.get('pk')
        return context_data

    def get_queryset(self):  # переопределяем queryset фильтруя по категории
        queryset = super(ProductsCategoryListView, self).get_queryset()
        return queryset.filter(category=self.kwargs.get('pk'))


# @user_passes_test(lambda x: x.is_superuser)
# def products_category_read(request, pk, page=1):  # вывод товаров выбранной категории
#     title = 'adm/товары категории'
#     products = Product.objects.filter(category=pk).order_by('-is_active', 'name')
#     products_page = get_paginator_page(products, page)
#     # if products.exists():
#     #     pk_category = products[0].category_id
#     pk_category = pk
#     content = {
#         'title': title,
#         'objects_of_category': products_page,  # загружать на странице сипсок  по категориям
#         'objects_of_type': None,  # не загружать на странице сипсок  по типам
#         'pk_category': pk_category  # для передачи pk категории в шаблон, что бы  потомвернуться к списку товаров
#     }
#     return render(request, 'adminapp/products.html', content)


class ProductsTypeListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 3

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'товары данного типа'
        context_data['objects_of_category'] = False
        context_data['objects_of_type'] = True
        context_data['pk_type'] = self.kwargs.get('pk')
        return context_data

    def get_queryset(self):
        queryset = super(ProductsTypeListView, self).get_queryset()
        return queryset.filter(type=self.kwargs.get('pk'))


# @user_passes_test(lambda x: x.is_superuser)
# def products_type_read(request, pk, page=1):  # вывод товаров выбранного типа
#     title = 'adm/товары типа'
#     products = Product.objects.filter(type=pk).order_by('-is_active', 'name')
#     products_page = get_paginator_page(products, page)
#     # if products.exists():
#     #     pk_type = products[0].type_id
#     pk_type = pk
#     content = {
#         'title': title,

adminapp/templates/adminapp/includes/adm_main_menu.html
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'main' %}"> <img src="{% static 'img/logo.png' %}"
                                                                              alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="about.html">about</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        product
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" href="{% url 'products:index' %}"> product list</a>
                                        <a class="dropdown-item" href="single-product.html">product details</a>

                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_3"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        pages
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">

                                        <a class="dropdown-item" href="checkout.html">product checkout</a>
                                        <a class="dropdown-item" href="{% url 'basket:main' %}">Корзина</a>
                                        <a class="dropdown-item" href="confirmation.html">confirmation</a>
                                        <a class="dropdown-item" href="elements.html">elements</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_2"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        blog
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                        <a class="dropdown-item" href="blog.html"> blog</a>
                                        <a class="dropdown-item" href="single-blog.html">Single blog</a>
                                    </div>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                                </li>
                                {% include 'mainapp/includes/inc_login_in_main_menu.html' %}
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <a data-placement="bottom" title="{{ basket_itm.0.total_cost|floatformat:0 }} &#8381"
                               href="{% url 'basket:main' %}">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                                {% if basket_itm %}
                                    <span class="badge badge-pill badge-primary ">{{ basket_itm.0.total_quantity }}</span>
                                {% endif %}
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->

adminapp/templates/adminapp/includes/inc_adm_main_menu.html
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'main' %}"> <img src="{% static 'img/logo.png' %}"
                                                                              alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'main' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="about.html">about</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        product
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" href="{% url 'products:index' %}"> product list</a>
                                        <a class="dropdown-item" href="single-product.html">product details</a>

                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_3"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        pages
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">

                                        <a class="dropdown-item" href="checkout.html">product checkout</a>
                                        <a class="dropdown-item" href="{% url 'basket:main' %}">Корзина</a>
                                        <a class="dropdown-item" href="confirmation.html">confirmation</a>
                                        <a class="dropdown-item" href="elements.html">elements</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_2"
                                       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        blog
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                        <a class="dropdown-item" href="blog.html"> blog</a>
                                        <a class="dropdown-item" href="single-blog.html">Single blog</a>
                                    </div>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                                </li>
                                {% include 'mainapp/includes/inc_login_in_main_menu.html' %}
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <a data-placement="bottom" title="{{ basket_itm.0.total_cost|floatformat:0 }} &#8381"
                               href="{% url 'basket:main' %}">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                                {% if basket_itm %}
                                    <span class="badge badge-pill badge-primary ">{{ basket_itm.0.total_quantity }}</span>
                                {% endif %}
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->

adminapp/templates/adminapp/includes/inc_categories_paginations.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            {% if page_obj.has_previous %}
                <a href="{% url 'admin:categories_read_page'  page_obj.previous_page_number %}"
                   class="page-link genric-btn primary">Назад</a>
            {% endif %}
        </li>
        <li class="page-item">
                                    <span class="page-link genric-btn primary">
                                        страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                                    </span>
        </li>
        <li class="page-item">
            {% if page_obj.has_next %}
                <a href="{% url 'admin:categories_read_page' page_obj.next_page_number %}"
                   class="page-link genric-btn primary">Вперёд</a>
            {% endif %}
        </li>
    </ul>
</nav>

adminapp/templates/adminapp/includes/inc_paginations.html
    <nav aria-label="Page navigation example" style="padding-bottom: 1em; padding-top: 1em;">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if objects.has_previous %}
                    <a href="{% url 'admin:users_read_page'  objects.previous_page_number %}"
                       class="page-link genric-btn primary">Назад</a>
                {% endif %}
            </li>
            <li class="page-item">
                                    <span class="page-link genric-btn primary">
                                        страница {{ objects.number }} из {{ objects.paginator.num_pages }}
                                    </span>
            </li>
            <li class="page-item">
                {% if objects.has_next %}
                    <a href="{% url 'admin:users_read_page' objects.next_page_number %}"
                       class="page-link genric-btn primary">Вперёд</a>
                {% endif %}
            </li>
        </ul>
    </nav>