PillowMarket/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main),
    path('products/', mainapp.products),
    path('contact/', mainapp.contact),
    path('admin/', admin.site.urls),

]

adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.admin, name='admin'),

    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users_read, name='users_read'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users_read'),
    # path('users/read/page/<page>/', adminapp.users_read, name='users_read_page'),
    path('users/read/page/<page>/', adminapp.UsersListView.as_view(), name='users_read_page'),
    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('product/create/ofcategory/<int:pk>/', adminapp.ProductCreateOfCategoryView.as_view(), name='product_create_ofcategory'),
    path('product/create/oftype/<int:pk>/', adminapp.ProductCreateOfTypeView.as_view(), name='product_create_oftype'),
    # path('products/read/category/<int:pk>/', adminapp.products_category_read, name='products_category_read'),
    path('products/read/category/<int:pk>/', adminapp.ProductsCategoryListView.as_view(), name='products_category_read'),
    # path('products/read/category/<int:pk>/page/<page>/', adminapp.products_category_read, name='products_category_read_page'),
    path('products/read/category/<int:pk>/page/<page>/', adminapp.ProductsCategoryListView.as_view(), name='products_category_read_page'),
    # path('products/read/type/<int:pk>/', adminapp.products_type_read, name='products_type_read'),
    path('products/read/type/<int:pk>/', adminapp.ProductsTypeListView.as_view(), name='products_type_read'),
    # path('products/read/type/<int:pk>/page/<page>/', adminapp.products_type_read, name='products_type_read_read_page'),
    path('products/read/type/<int:pk>/page/<page>/', adminapp.ProductsTypeListView.as_view(), name='products_type_read_page'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    # path('products/delete/ct/<int:pk_category>/<int:pk>/', adminapp.product_ct_delete, name='product_ct_delete'),
    path('products/delete/ct/<int:pk>/', adminapp.ProductOfCategoryDeleteView.as_view(), name='product_ct_delete'),
    # path('products/delete/tp/<int:pk_type>/<int:pk>/', adminapp.product_tp_delete, name='product_tp_delete'),
    path('products/delete/tp/<int:pk>/', adminapp.ProductOfTypeDeleteView.as_view(), name='product_tp_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.CategoriesReadListView.as_view(), name='categories_read'),
    path('categories/read/page/<page>/', adminapp.CategoriesReadListView.as_view(), name='categories_read_page'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('types/create/', adminapp.TypeCreateView.as_view(), name='type_create'),
    # path('types/read/', adminapp.types_read, name='types_read'),
    path('types/read/', adminapp.TypesReadListView.as_view(), name='types_read'),
    # path('types/read/page/<page>/', adminapp.types_read, name='types_read_page'),
    path('types/read/page/<page>/', adminapp.TypesReadListView.as_view(), name='types_read_page'),
    path('types/update/<int:pk>/', adminapp.TypeUpdateView.as_view(), name='type_update'),
    path('types/delete/<int:pk>/', adminapp.TypeDeleteView.as_view(), name='type_delete'),

]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('registry/', authapp.registry, name='registry'),
    path('edit/', authapp.edit, name='edit'),
    path('verification/<email>/<activation_key>/', authapp.verification, name='verification')

]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('page/<page>/', mainapp.products, name='index_page'),

   path('<int:pk_cat>/', mainapp.products, name='pr_category'),
   path('<int:pk_cat>/page/<page>/', mainapp.products, name='pr_category_page'),

   # path('<int:pk_type>/', mainapp.products, name='pr_type'),

   path('single_product/<int:pk>/', mainapp.SingleProductDetailView.as_view(), name='single_product'),
]

orderapp/urls.py
from django.urls import path

import orderapp.views as orderapp

app_name = 'orderapp'

urlpatterns = [
    path('', orderapp.OrderList.as_view(), name='orders_list'),
    path('create/', orderapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<pk>/', orderapp.OrderRead.as_view(), name='order_read'),
    path('update/<pk>/', orderapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<pk>/', orderapp.OrderItemsDelete.as_view(), name='order_delete'),
    path('forming/<pk>/', orderapp.order_forming_complete, name='order_forming_complete'),
]

pillowmarket/urls.py
# from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='Активна', default=True)

    class Meta:  # для отображения в админке имя таблицы
        verbose_name = 'Категория товаров'
        verbose_name_plural = 'Категории товаров'

    def __str__(self):
        return self.name


class ProductType(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='Активна', default=True)

    class Meta:
        verbose_name = 'Тип материала товаров'
        verbose_name_plural = 'Тип материалов товаров'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='Категория товара')
    type = models.ForeignKey(ProductType, on_delete=models.ForeignKey, verbose_name='Материал')
    name = models.CharField(verbose_name='Название товара', max_length=128)
    image = models.ImageField(verbose_name='Расположение фото', upload_to='foto_product',
                              blank=True)  # upload_to папк куда загрузится фото при добавлении товара и указания фото
    # удалить кр. описание если не понадобится
    short_desc = models.CharField(verbose_name='краткое описание товара', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание товара', blank=True)
    price = models.DecimalField(verbose_name='цена товара', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='Активна', default=True)

    class Meta:  # для отображения в админке имя таблицы
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
import random

from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import DetailView

from mainapp.models import Product, ProductCategory, ProductType


def get_trending_product():
    """
    Trending products in main page
    :return:
    """
    _products = Product.objects.filter(is_active=True)
    trend = random.sample(list(_products), 6)  # [0]
    return trend


def get_products_in_main_page():
    """
    3 products in main page of main category only
    :return: 
    """
    main_prod = random.sample(list(Product.objects.filter(category_id=1, is_active=True)), 3)
    return main_prod


# def get_same_products()
#     """
#     same products in single product page
#     :return:
#     """
#     random
#     same = Product.objects.filter(category_id='#').exclude(pk='#')[:4]
#     return same


def main(request):
    title = 'Магазин Подушек'
    main_products = get_products_in_main_page()  # выведем на главной 3  товара
    trending_products = get_trending_product()  # выведем на главной 6 тренд. товара
    variable_date = {
        'title': title,
        'main_products': main_products,
        'trending_products': trending_products
    }
    return render(request, 'mainapp/index.html', variable_date)


def get_paginator_page(_products, _page):
    _paginator = Paginator(_products, 4)
    try:  # вывести страницу продуктов номер page
        _products_paginator = _paginator.page(_page)
    except PageNotAnInteger:  # если страница не целое число, то вывести первую
        _products_paginator = _paginator.page(1)
    except EmptyPage:  # если больше максимальной, то последнюю
        _products_paginator = _paginator.page(_paginator.num_pages)
    return _products_paginator


# сделать фильтрацию по типам последовательно после категорий
# добавить третье меню для выбора типа и направления сортировки (название, цена, скидки)
def products(request, pk_cat=None, page=1):
    title = 'Товары'
    links_menu_type = ProductType.objects.filter(is_active=True)
    links_menu_category = ProductCategory.objects.filter(is_active=True)

    if pk_cat is None:
        products_set = Product.objects.filter(is_active=True, category__is_active=True)
        products_paginator = get_paginator_page(products_set, page)

    if pk_cat is not None:
        if pk_cat == 0:
            # при выборе дрю категории или заходе на продукты, эта строка не загружается
            category_of_products_set = {"name": "все!"}
            products_set = Product.objects.filter(is_active=True, category__is_active=True)
            products_paginator = get_paginator_page(products_set, page)
            # type_of_products_set = {"name": "все"}
        else:
            category_of_products_set = get_object_or_404(ProductCategory, pk=pk_cat)
            # type_of_products_set = get_object_or_404(ProductType, pk= #_key)
            products_set = Product.objects.filter(category=category_of_products_set, is_active=True,
                                                  category__is_active=True)
            products_paginator = get_paginator_page(products_set, page)

        variable_date = {
            'title': title,
            'pk_cat': pk_cat,
            'links_menu_category': links_menu_category,
            'links_menu_type': links_menu_type,
            "products_set": products_paginator,
            'category_of_products_set': category_of_products_set,
        }
        return render(request, 'mainapp/product_list.html', variable_date)

    variable_date = {
        'title': title,
        'pk_cat': pk_cat,
        'links_menu_category': links_menu_category,
        'links_menu_type': links_menu_type,
        'products_set': products_paginator,  # что бы при первом открывании продуктов, были показаны   все продукты
    }
    return render(request, 'mainapp/product_list.html', variable_date)


def contact(request):
    title = 'Контакты'
    variable_date = {
        'title': title,
    }
    return render(request, 'mainapp/contact.html', variable_date)


class SingleProductDetailView(DetailView):
    model = Product
    template_name = 'mainapp/single_product.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Товар'
        return context_data

# def single_product(request, pk_prod):
#     single_prod = get_object_or_404(Product, pk=pk_prod)
#     title = single_prod.name
#     basket_itm = get_basket_itm(request.user)
#     variable_date = {
#         'title': title,
#         'basket_itm': basket_itm,
#         'single_prod': single_prod
#     }
#     return render(request, 'mainapp/single_product.html', variable_date)

mainapp/templates/mainapp/includes/inc_login_in_main_menu.html
{% if user.is_authenticated %}
    {% if user.is_superuser %}
        <li class="nav-item">
            <a class="nav-link" style="color: #8b010c;
               text-decoration-line: underline"
               href="{% url 'adminapp:admin' %}">
                Админка
            </a>
        </li>
    {% endif %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown_4"
           role="button" data-toggle="dropdown" aria-haspopup="true"
           aria-expanded="false" style="font-weight: bold">
            {% if user.first_name %}
                {{ user.first_name }}
            {% else %}
                {{ user.username }}
            {% endif %}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown_4">

            <a class="dropdown-item" href="{% url 'authapp:edit' %}">
                профиль
            </a>
            <a class="dropdown-item" href="{% url 'basket:main' %}">корзина</a>
            <a class="dropdown-item" href="{% url 'order:orders_list' %}">заказ</a>
            <a class="dropdown-item" href="elements.html">подтв</a>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'authapp:logout' %}">
            Выйти
        </a>
    </li>
{% else %}
    <li class="nav-item">
        <a class="nav-link" href="#">
            {{ '[имя]' }}
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'authapp:login' %}">
            Авторизуйтесь
        </a>
    </li>
{% endif %}

mainapp/templates/mainapp/includes/inc_menu_category.html
<p><a href="{% url 'products:pr_category' 0 %}">Все#</a></p>
{% for itm in links_menu_category %}
    <p><a href="{% url 'products:pr_category' itm.id %}">{{ itm.name }}</a></p>
{% endfor %}

mainapp/templates/mainapp/includes/inc_menu_type.html
<p><a href="{% url 'products:pr_type' 0 %}">Все</a></p>
{% for itm in links_menu_type %}
    <p><a href="{% url 'products:pr_type' itm.id %}">{{ itm.name }}</a></p>
{% endfor %}

mainapp/templates/mainapp/includes/inc_paginations.html
{% if pk_cat is None %}
    <nav aria-label="Page navigation example" style="padding-bottom: 1em; padding-top: 1em;">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if products_set.has_previous %}
                    <a href="{% url 'mainapp:index_page'  products_set.previous_page_number %}"
                       class="page-link genric-btn primary">Назад</a>
                {% endif %}
            </li>
            <li class="page-item">
                                    <span class="page-link genric-btn primary">
                                        страница {{ products_set.number }} из {{ products_set.paginator.num_pages }}
                                    </span>
            </li>
            <li class="page-item">
                {% if products_set.has_next %}
                    <a href="{% url 'mainapp:index_page' products_set.next_page_number %}"
                       class="page-link genric-btn primary">Вперёд</a>
                {% endif %}
            </li>
        </ul>
    </nav>
{% else %}
    <nav aria-label="Page navigation example" style="padding-bottom: 1em; padding-top: 1em;">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if products_set.has_previous %}
                    <a href="{% url 'mainapp:pr_category_page' pk_cat products_set.previous_page_number %}"
                       class="page-link genric-btn primary">Назад</a>
                {% endif %}
            </li>
            <li class="page-item">
                                    <span class="page-link genric-btn primary">
                                        страница {{ products_set.number }} из {{ products_set.paginator.num_pages }}
                                    </span>
            </li>
            <li class="page-item">
                {% if products_set.has_next %}
                    <a href="{% url 'mainapp:pr_category_page' pk_cat products_set.next_page_number %}"
                       class="page-link genric-btn primary">Вперёд</a>
                {% endif %}
            </li>
        </ul>
    </nav>
{% endif %}

mainapp/templates/mainapp/includes/paginations.html
{% if pk_cat is None %}
    <nav aria-label="Page navigation example" style="padding-bottom: 1em; padding-top: 1em;">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if products_set.has_previous %}
                    <a href="{% url 'mainapp:index_page'  products_set.previous_page_number %}"
                       class="page-link genric-btn primary">Назад</a>
                {% endif %}
            </li>
            <li class="page-item">
                                    <span class="page-link genric-btn primary">
                                        страница {{ products_set.number }} из {{ products_set.paginator.num_pages }}
                                    </span>
            </li>
            <li class="page-item">
                {% if products_set.has_next %}
                    <a href="{% url 'mainapp:index_page' products_set.next_page_number %}"
                       class="page-link genric-btn primary">Вперёд</a>
                {% endif %}
            </li>
        </ul>
    </nav>
{% else %}
    <nav aria-label="Page navigation example" style="padding-bottom: 1em; padding-top: 1em;">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if products_set.has_previous %}
                    <a href="{% url 'mainapp:pr_category_page' pk_cat products_set.previous_page_number %}"
                       class="page-link genric-btn primary">Назад</a>
                {% endif %}
            </li>
            <li class="page-item">
                                    <span class="page-link genric-btn primary">
                                        страница {{ products_set.number }} из {{ products_set.paginator.num_pages }}
                                    </span>
            </li>
            <li class="page-item">
                {% if products_set.has_next %}
                    <a href="{% url 'mainapp:pr_category_page' pk_cat products_set.next_page_number %}"
                       class="page-link genric-btn primary">Вперёд</a>
                {% endif %}
            </li>
        </ul>
    </nav>
{% endif %}