PillowMarket/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main),
    path('products/', mainapp.products),
    path('contact/', mainapp.contact),
    path('admin/', admin.site.urls),

]

adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.admin, name='admin'),

    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users_read, name='users_read'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users_read'),
    # path('users/read/page/<page>/', adminapp.users_read, name='users_read_page'),
    path('users/read/page/<page>/', adminapp.UsersListView.as_view(), name='users_read_page'),
    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('product/create/ofcategory/<int:pk>/', adminapp.ProductCreateOfCategoryView.as_view(), name='product_create_ofcategory'),
    path('product/create/oftype/<int:pk>/', adminapp.ProductCreateOfTypeView.as_view(), name='product_create_oftype'),
    # path('products/read/category/<int:pk>/', adminapp.products_category_read, name='products_category_read'),
    path('products/read/category/<int:pk>/', adminapp.ProductsCategoryListView.as_view(), name='products_category_read'),
    # path('products/read/category/<int:pk>/page/<page>/', adminapp.products_category_read, name='products_category_read_page'),
    path('products/read/category/<int:pk>/page/<page>/', adminapp.ProductsCategoryListView.as_view(), name='products_category_read_page'),
    # path('products/read/type/<int:pk>/', adminapp.products_type_read, name='products_type_read'),
    path('products/read/type/<int:pk>/', adminapp.ProductsTypeListView.as_view(), name='products_type_read'),
    # path('products/read/type/<int:pk>/page/<page>/', adminapp.products_type_read, name='products_type_read_read_page'),
    path('products/read/type/<int:pk>/page/<page>/', adminapp.ProductsTypeListView.as_view(), name='products_type_read_page'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    # path('products/delete/ct/<int:pk_category>/<int:pk>/', adminapp.product_ct_delete, name='product_ct_delete'),
    path('products/delete/ct/<int:pk>/', adminapp.ProductOfCategoryDeleteView.as_view(), name='product_ct_delete'),
    # path('products/delete/tp/<int:pk_type>/<int:pk>/', adminapp.product_tp_delete, name='product_tp_delete'),
    path('products/delete/tp/<int:pk>/', adminapp.ProductOfTypeDeleteView.as_view(), name='product_tp_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.CategoriesReadListView.as_view(), name='categories_read'),
    path('categories/read/page/<page>/', adminapp.CategoriesReadListView.as_view(), name='categories_read_page'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('types/create/', adminapp.TypeCreateView.as_view(), name='type_create'),
    # path('types/read/', adminapp.types_read, name='types_read'),
    path('types/read/', adminapp.TypesReadListView.as_view(), name='types_read'),
    # path('types/read/page/<page>/', adminapp.types_read, name='types_read_page'),
    path('types/read/page/<page>/', adminapp.TypesReadListView.as_view(), name='types_read_page'),
    path('types/update/<int:pk>/', adminapp.TypeUpdateView.as_view(), name='type_update'),
    path('types/delete/<int:pk>/', adminapp.TypeDeleteView.as_view(), name='type_delete'),

]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('registry/', authapp.registry, name='registry'),
    path('edit/', authapp.edit, name='edit'),
    path('verification/<email>/<activation_key>/', authapp.verification, name='verification')

]

pillowmarket/urls.py
# from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/forms.py
from django import forms

from authapp.forms import BuyerEditForm
from authapp.models import Buyer
from mainapp.models import ProductCategory, ProductType, Product


class AdminEditFormBuyer(BuyerEditForm):
    class Meta:
        model = Buyer
        fields = '__all__'


class AdminEditFormProductCategory(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AdminEditFormProductCategory, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class AdminEditFormProductType(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AdminEditFormProductType, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class AdminEditFormProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AdminEditFormProduct, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from adminapp.forms import AdminEditFormProductCategory, AdminEditFormProductType, \
    AdminEditFormProduct, AdminEditFormBuyer
from authapp.forms import BuyerRegistyForm
from authapp.models import Buyer
from mainapp.models import ProductCategory, ProductType, Product


@user_passes_test(lambda x: x.is_superuser)
def admin(request):
    title = 'adm/ Админка'
    content = {
        'title': title,
    }
    return render(request, 'adminapp/admin.html', content)


# def get_paginator_page(_objs, _page):
#     _paginator = Paginator(_objs, 2)
#     try:  # вывести страницу продуктов номер page
#         _objs_paginator = _paginator.page(_page)
#     except PageNotAnInteger:  # если страница не целое число, то вывести первую
#         _objs_paginator = _paginator.page(1)
#     except EmptyPage:  # если больше максимальной, то последнюю
#         _objs_paginator = _paginator.page(_paginator.num_pages)
#     return _objs_paginator


# users =============== users =============== users =============== users =============== users
class UsersListView(ListView):
    model = Buyer
    template_name = 'adminapp/users.html'  # в шаблон теперь передаётся object_list

    # переопределяем встроенный метод, накладываем декоратор
    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    # добавляем данные в контекст
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Пользователи'
        return context_data

    # пагинатор, указвываем колю-во на странице, на страницу передаётся page_obj
    paginate_by = 3


# @user_passes_test(lambda x: x.is_superuser)
# def users_read(request, page=1):
#     title = 'adm/пользователи'
#     users_list = Buyer.objects.all().order_by('-is_active', '-is_superuser', 'username', 'first_name', 'last_name')
#     users_list_paginator = get_paginator_page(users_list, page)
#     content = {
#         'title': title,
#         'objects': users_list_paginator
#     }
#     return render(request, 'adminapp/users.html', content)

class UserCreateView(CreateView):
    model = Buyer
    template_name = 'adminapp/user.html'
    success_url = reverse_lazy('admin:users_read')
    form_class = BuyerRegistyForm

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создать пользователя'
        return context_data


# @user_passes_test(lambda x: x.is_superuser)
# def user_create(request):
#     title = 'adm/Новый пользователь'
#     if request.method == 'POST':
#         user_form = BuyerRegistyForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin:users_read'))
#     else:
#         user_form = BuyerRegistyForm()
#     content = {
#         'title': title,
#         'objects': user_form
#     }
#     return render(request, 'adminapp/user.html', content)


class UserUpdateView(UpdateView):
    model = Buyer
    template_name = 'adminapp/user.html'
    success_url = reverse_lazy('admin:users_read')
    form_class = AdminEditFormBuyer

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Просмотр/Редактирование пользователя'
        return context_data


# @user_passes_test(lambda x: x.is_superuser)
# def user_update(request, pk):
#     title = 'adm/Редактирование пользователя'
#     user = get_object_or_404(Buyer, pk=pk)
#
#     if request.method == 'POST':
#         user_form = AdminEditFormBuyer(request.POST, request.FILES, instance=user)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin:user_update', args=[user.pk]))
#     else:
#         user_form = AdminEditFormBuyer(instance=user)
#     content = {
#         'title': title,
#         'objects': user_form,
#     }
#     return render(request, 'adminapp/user.html', content)


class UserDeleteView(DeleteView):
    model = Buyer
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin:users_read')
    form_class = AdminEditFormBuyer

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Удаление пользователя'
        return context_data

    # переопределяем метод удаления (на is_active)
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda x: x.is_superuser)
# def user_delete(request, pk):
#     title = 'adm/Удаление пользователя'
#     user = get_object_or_404(Buyer, pk=pk)
#     if user.is_active is True:
#         if request.method == 'POST':
#             user.is_active = False
#             user.save()
#             return HttpResponseRedirect(reverse('admin:users_read'))
#         content = {
#             'title': title,
#             'object_del': user
#         }
#         return render(request, 'adminapp/user_delete.html', content)
#     else:
#         # if request.method == 'POST':
#         user.is_active = True
#         user.save()
#         return HttpResponseRedirect(reverse('admin:users_read'))


# products =============== products =============== products =============== products
# просмотр совмещён с редактированием, сделать отдельно
# class ProductsCategoryDetailView(DetailView):
#     model = Product
#     template_name = 'adminapp/product.html'
#
#     @method_decorator(user_passes_test(lambda x: x.is_superuser))
#     def dispatch(self, *args, **kwargs):
#         return super().dispatch(*args, **kwargs)
#
#     def get_context_data(self, **kwargs):
#         context_data = super().get_context_data(**kwargs)
#         context_data['from_category'] = True
#         return context_data

class ProductsCategoryListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 3

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'товары данной категории'
        context_data['objects_of_category'] = True  # для выбора нужного цикла в шаблоне
        context_data['objects_of_type'] = False  # для выбора нужного цикла в шаблоне
        context_data['pk_category'] = self.kwargs.get('pk')
        return context_data

    def get_queryset(self):  # переопределяем queryset фильтруя по категории
        queryset = super(ProductsCategoryListView, self).get_queryset()
        return queryset.filter(category=self.kwargs.get('pk'))


# @user_passes_test(lambda x: x.is_superuser)
# def products_category_read(request, pk, page=1):  # вывод товаров выбранной категории
#     title = 'adm/товары категории'
#     products = Product.objects.filter(category=pk).order_by('-is_active', 'name')
#     products_page = get_paginator_page(products, page)
#     # if products.exists():
#     #     pk_category = products[0].category_id
#     pk_category = pk
#     content = {
#         'title': title,
#         'objects_of_category': products_page,  # загружать на странице сипсок  по категориям
#         'objects_of_type': None,  # не загружать на странице сипсок  по типам
#         'pk_category': pk_category  # для передачи pk категории в шаблон, что бы  потомвернуться к списку товаров
#     }
#     return render(request, 'adminapp/products.html', content)


class ProductsTypeListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 3

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'товары данного типа'
        context_data['objects_of_category'] = False
        context_data['objects_of_type'] = True
        context_data['pk_type'] = self.kwargs.get('pk')
        return context_data

    def get_queryset(self):
        queryset = super(ProductsTypeListView, self).get_queryset()
        return queryset.filter(type=self.kwargs.get('pk'))


# @user_passes_test(lambda x: x.is_superuser)
# def products_type_read(request, pk, page=1):  # вывод товаров выбранного типа
#     title = 'adm/товары типа'
#     products = Product.objects.filter(type=pk).order_by('-is_active', 'name')
#     products_page = get_paginator_page(products, page)
#     # if products.exists():
#     #     pk_type = products[0].type_id
#     pk_type = pk
#     content = {
#         'title': title,

adminapp/templates/adminapp/admin.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content_adm %}
    <a href="{% url 'admin:users_read' %}" class="genric-btn primary rounded">пользователи</a>
    <a href="{% url 'admin:categories_read' %}" class="genric-btn primary rounded">Категории</a>
    <a href="{% url 'admin:types_read' %}" class="genric-btn primary rounded">Типы</a>
    <a href="{% url 'admin:user_create' %}" class="genric-btn success circle">+ Создать пользователя</a>
    <a href="{% url 'admin:category_create' %}" class="genric-btn success circle">+ Создать категорию</a>
    <a href="{% url 'admin:type_create' %}" class="genric-btn success circle">+ Создать тип</a>
{% endblock content_adm %}

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content_adm %}
    <a href="{% url 'admin:admin' %}" class="genric-btn primary rounded">Админка</a>
    <a href="{% url 'admin:category_create' %}" class="genric-btn success circle">+ Создать категорию</a>
    {% include 'adminapp/includes/inc_categories_paginations.html' %}
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">id</th>
            <th scope="col">Название</th>
            <th scope="col">Описание</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr data-href="{% url 'admin:products_category_read' object.id %}"
                title="Выбрать все товары данной категории"
                bgcolor="{% if not object.is_active %}#fa8072{% endif %}">
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ object.id }}</td>
                <td>
                    <a href="{% url 'admin:category_update' object.pk %}" class="btn badge-primary link-edit"
                       title="Редактировать категорию">
                        {{ object.name }}
                    </a>
                </td>
                <td>{{ object.description }}</td>
                <td>
                    {% if object.is_active %}
                        <a href="{% url 'admin:category_delete' object.pk %}"
                           class="btn btn-outline-danger ti-trash link-edit"
                           title="Удалить категорию"></a>
                    {% else %}
                        <a href="{% url 'admin:category_delete' object.pk %}"
                           class="btn badge-success ti-plus link-edit"
                           title="Восстановить категорию"></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content_adm %}

adminapp/templates/adminapp/category.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content_adm %}
    <div class="container">
        <div class="col-md-auto">
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-outline-success form-control" value="сохранить">
            </form>

            <a href="{% url 'admin:categories_read' %}" class="btn btn-outline-info form-control last-related">Вернуться
                к категориям</a>
        </div>
    </div>
{% endblock content_adm %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content_adm %}
    {% if object.is_active %}
        <div>
            Уверены, что хотите удалить товар: <strong>{{ object.name }}</strong>?
            {% if pk_category %}
                <form action="{% url 'admin:product_ct_delete' object.pk  %} " method="post">
            {% endif %}
            {% if pk_type %}
                <form action="{% url 'admin:product_tp_delete' object.pk %} " method="post">
            {% endif %}
            {% csrf_token %}
            <input type="submit" value="удалить" class="btn btn-danger">
            </form>
            <button class="btn btn-success">
                {% if pk_category %}
                    <a href="{% url 'admin:products_category_read' object.category_id %}">отмена</a>
                {% endif %}
                {% if pk_type %}
                    <a href="{% url 'admin:products_type_read' object.type_id %}">отмена</a>
                {% endif %}
            </button>
        </div>
    {% else %}
        <div>
            Уверены, что хотите восстановить товар: <strong>{{ object.name }}</strong>?
            {% if pk_category %}
                <form action="{% url 'admin:product_ct_delete' object.pk  %} " method="post">
            {% endif %}
            {% if pk_type %}
                <form action="{% url 'admin:product_tp_delete' object.pk %} " method="post">
            {% endif %}
            {% csrf_token %}
            <input type="submit" value="восстановить" class="btn btn-danger">
            </form>
            <button class="btn btn-success">
                {% if pk_category %}
                    <a href="{% url 'admin:products_category_read' object.category_id %}">отмена</a>
                {% endif %}
                {% if pk_type %}
                    <a href="{% url 'admin:products_type_read' object.type_id %}">отмена</a>
                {% endif %}
            </button>
        </div>
    {% endif %}

{% endblock content_adm %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content_adm %}
    {% if objects_of_category %}
        <a href="{% url 'admin:categories_read' %}" class="genric-btn primary rounded">Категории</a>
        <a href="{% url 'admin:product_create_ofcategory' pk_category %}" class="genric-btn success circle">+ Создать товар</a>
        {% include 'adminapp/includes/inc_products_category_paginations.html' %}
    {% endif %}
    {% if objects_of_type %}
        <a href="{% url 'admin:types_read' %}" class="genric-btn primary rounded">Типы</a>
        <a href="{% url 'admin:product_create_oftype' pk_type %}" class="genric-btn success circle">+ Создать товар</a>
        {% include 'adminapp/includes/inc_products_type_paginations.html' %}
    {% endif %}
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">id</th>
            <th scope="col">name</th>
            <th scope="col">Кр. описание</th>
            {% if objects_of_category %}
                <th scope="col">Тип</th>
            {% endif %}
            {% if objects_of_type %}
                <th scope="col">Категория</th>
            {% endif %}
            <th scope="col">количество</th>
            <th scope="col">Цена</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% if objects_of_category %}
            {#        цикл загружается когда продукты выбраны по категории#}
            {% for object in object_list %}
                <tr bgcolor="{% if not object.is_active %}#fa8072 {% endif %}">
                    <th scope="row">{{ forloop.counter }}c</th>
                    <td>{{ object.id }}</td>
                    <td>
                        <a href="{% url 'admin:product_update' object.pk %}" class="btn badge-primary link-edit"
                           title="Редактировать товар">
                            {{ object.name }}
                        </a>
                    </td>
                    <td>{{ object.short_desc }}</td>
                    {#                    <td>{{ object.category }}</td>#}
                    <td>{{ object.type }}</td>
                    <td>{{ object.quantity }}</td>
                    <td>{{ object.price }}</td>
                    <td>
                        {% if object.is_active %}
                            <a href="{% url 'admin:product_ct_delete' object.pk %}"
                               class="btn btn-outline-danger ti-trash link-edit"
                               title="Удалить товар"></a>
                        {% else %}
                            <a href="{% url 'admin:product_ct_delete' object.pk %}"
                               class="btn badge-success ti-plus link-edit"
                               title="Восстановить товар"></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
        {% if objects_of_type %}
            {#        цикл загружается когда продукты выбраны по типу#}
            {% for object in object_list %}
                <tr bgcolor="{% if not object.is_active %} #fa8072{% endif %}">
                    <th scope="row">{{ forloop.counter }}t</th>
                    <td>{{ object.id }}</td>
                    <td>
                        <a href="{% url 'admin:product_update' object.pk %}" class="btn badge-primary link-edit"
                           title="Редактировать товар">
                            {{ object.name }}
                        </a>
                    </td>
                    <td>{{ object.short_desc }}</td>
                    <td>{{ object.category }}</td>
                    {#                    <td>{{ object.type }}</td>#}
                    <td>{{ object.quantity }}</td>
                    <td>{{ object.price }}</td>
                    <td>
                        {% if object.is_active %}
                            <a href="{% url 'admin:product_tp_delete' object.pk %}"
                               class="btn btn-outline-danger ti-trash link-edit"
                               title="Удалить товар"></a>
                        {% else %}
                            <a href="{% url 'admin:product_tp_delete' object.pk %}"
                               class="btn badge-success ti-plus link-edit"
                               title="Восстановить товар"></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% endif %}


        </tbody>
    </table>
{% endblock content_adm %}

adminapp/templates/adminapp/types.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content_adm %}
    <a href="{% url 'admin:admin' %}" class="genric-btn primary rounded">Админка</a>
    <a href="{% url 'admin:type_create' %}" class="genric-btn success circle">+ Создать тип</a>
    {% include 'adminapp/includes/inc_types_paginations.html' %}
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">id</th>
            <th scope="col">Название</th>
            <th scope="col">Описание</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr data-href="{% url 'adminapp:products_type_read' object.pk %}"
                title="Выбрать все товары данного типа"
                bgcolor="{% if not object.is_active %} #fa8072 {% endif %}">
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ object.id }}</td>
                <td>
                    <a href="{% url 'admin:type_update' object.pk %}" class="btn badge-primary link-edit"
                       title="Редактировать тип">
                        {{ object.name }}
                    </a>
                </td>
                <td>{{ object.description }}</td>
                <td>
                    {% if object.is_active %}
                        <a href="{% url 'admin:type_delete' object.pk %}"
                           class="btn btn-outline-danger ti-trash link-edit"
                           title="Удалить тип"></a>
                    {% else %}
                        <a href="{% url 'admin:type_delete' object.pk %}"
                           class="btn badge-success ti-plus link-edit"
                           title="Восстановить тип"></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content_adm %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content_adm %}
    <a href="{% url 'admin:admin' %}" class="genric-btn primary rounded">Админка</a>
    <a href="{% url 'admin:user_create' %}" class="genric-btn success circle">+ Создать пользователя</a>
{#    <h1>доп. контекст:{{ qwerty }}</h1>#}
    {% include 'adminapp/includes/inc_users_paginations.html' %}
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">id</th>
            <th scope="col">username</th>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            <th scope="col">Доступ</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr data-href="#" bgcolor="{% if not object.is_active %} #fa8072 {% endif %} ">
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ object.id }}</td>
                <td>
                    <a href="{% url 'admin:user_update' object.pk %}" class="btn badge-primary link-edit"
                       title="Редактировать пользователя">
                        {{ object.username }}
                    </a>
                </td>
                <td>{{ object.first_name }}</td>
                <td>{{ object.last_name }}</td>
                <td>
                    {% if object.is_active %}
                        Разрешён
                    {% else %}
                        Запрещён
                    {% endif %}
                </td>
                <td>
                    {% if object.is_active %}
                        <a href="{% url 'admin:user_delete' object.pk %}"
                           class="btn btn-outline-danger ti-trash link-edit"
                           title="Удалить пользователя"></a>
                    {% else %}
                        <a href="{% url 'admin:user_delete' object.pk %}"
                           class="btn badge-success ti-plus link-edit"
                           title="Восстановить пользователя"></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content_adm %}