PillowMarket/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main),
    path('products/', mainapp.products),
    path('contact/', mainapp.contact),
    path('admin/', admin.site.urls),

]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('registry/', authapp.registry, name='registry'),
    path('edit/', authapp.edit, name='edit'),
    path('verification/<email>/<activation_key>/', authapp.verification, name='verification')

]

orderapp/urls.py
from django.urls import path

import orderapp.views as orderapp

app_name = 'orderapp'

urlpatterns = [
    path('', orderapp.OrderList.as_view(), name='orders_list'),
    path('create/', orderapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<pk>/', orderapp.OrderRead.as_view(), name='order_read'),
    path('update/<pk>/', orderapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<pk>/', orderapp.OrderItemsDelete.as_view(), name='order_delete'),
    path('forming/<pk>/', orderapp.order_forming_complete, name='order_forming_complete'),
]

pillowmarket/urls.py
# from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orderapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product

""" 
(!) created updated is_active  - данные поля создавать во всех моделях, с 
которыми работает пользователь (!)
"""


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    DONE = 'DN'
    CANCEL = 'CNC'
    ORDER_STATUSES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCEED, 'отправлен в обработку'),
        (PROCEEDED, 'обработан'),
        (PAID, 'оплачен'),
        (READY, 'готов к выдаче'),
        (DONE, 'выдан'),
        (CANCEL, 'отменён'),
    )
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                              verbose_name='Покупатель')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    status = models.CharField(max_length=3, choices=ORDER_STATUSES,
                              default=FORMING)
    is_active = models.BooleanField(default=True, verbose_name='Активен')

    class Meta:
        # сортировка по умолчанию от более новых к старым заказам:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий  заказ: #{self.id}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    # переопределяем метод, удаляющий объект...
    def delete(self):
        for item in self.orderitems.select_related():
            # возвращаем кол.-во товара из заказа на склад
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False  # ... на неактивный
        self.save()


# аналогично корзине - заказ Order состоит из отдельных заказов OrderItem
# кажого продукта
class OrderItem(models.Model):
    # связываем модель с основной. При удалении основного, данный экзампляр
    # тоже удалится
    order = models.ForeignKey(Order, related_name="orderitems",
                              on_delete=models.CASCADE, verbose_name='позиция')
    product = models.ForeignKey(Product, verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

orderapp/forms.py
from django import forms

from orderapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        # все поля, кроме buyer, так как это увидит только сам покупатель
        exclude = ('buyer',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

orderapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from basketapp.models import Basket
from orderapp.forms import OrderItemForm
from orderapp.models import Order, OrderItem


# По умолчанию для ListView Django будет искать шаблон с именем вида:
# «<имя класса>_list.html».
# LoginRequiredMixin - добавляем миксин для доступа только залогиненным юзерам
class OrderList(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        """
        Переопределили метод «get_queryset()» для того, чтобы пользователь
        видел только свои заказы
        """
        return Order.objects.filter(buyer=self.request.user)


# Для классов CreateView и UpdateView шаблон должен иметь имя вида
# «<имя класса>_form.html»
class OrderItemsCreate(LoginRequiredMixin, CreateView):
    model = Order
    # в соответствии с моделью все поля, кроме пользователя buyer, создаются
    # автоматически, buyer добавим позже
    fields = []
    success_url = reverse_lazy('orderapp:orders_list')

    def get_queryset(self):
        return Order.objects.filter(buyer=self.request.user)

    # добавляем данные в контекст, пересобираем в одну форму OrderItemForm
    # из Order и OrderItem
    def get_context_data(self, **kwargs):
        context_data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        order_form_set = inlineformset_factory(Order, OrderItem,
                                               form=OrderItemForm, extra=1)
        if self.request.POST:  # если пост запрос, заполняем данными
            formset = order_form_set(self.request.POST)
        else:
            # из корзины собираем все позиции("товары-корзинки") пользователя(!)
            basket_items = Basket.get_items(self.request.user)
            if len(basket_items):  # если в корзине что-то есть
                # создаём форму заказа
                order_form_set = inlineformset_factory(Order, OrderItem,
                                                       form=OrderItemForm,
                                                       extra=len(basket_items))
                formset = order_form_set()
                # заполняем
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                # удаление собранных позиций из корзины. При удаление в данном
                # месте, возвращаясь в корзину после создания заказа, она будет
                # пуста
                basket_items.delete()
            else:
                formset = order_form_set()

        context_data['orderitems'] = formset  # если гет, то пустую форму
        context_data['title'] = 'заказ'
        return context_data

    def form_valid(self, form):  # в form главн. форма из get_context_data
        context = self.get_context_data()  # забраем контекст
        orderitems = context['orderitems']  # из него orderitems

        with transaction.atomic():
            # в форму добавляем пользователя из пост запроса
            form.instance.buyer = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderItemsUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    # в соответствии с моделью все поля, кроме пользователя buyer, создаются
    # автоматически, buyer добавим позже
    fields = []
    success_url = reverse_lazy('orderapp:orders_list')

    def get_queryset(self):
        return Order.objects.filter(buyer=self.request.user)

    # добавляем данные в контекст, пересобираем в одну форму OrderItemForm
    # из Order и OrderItem
    def get_context_data(self, **kwargs):
        context_data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        order_form_set = inlineformset_factory(Order, OrderItem,
                                               form=OrderItemForm, extra=1)
        if self.request.POST:  # если пост запрос, заполняем данными
            formset = order_form_set(self.request.POST, instance=self.object)
        else:
            formset = order_form_set(instance=self.object)

        context_data['orderitems'] = formset  # если гет, то пустую форму
        context_data['title'] = 'редактировать заказ'
        return context_data

    def form_valid(self, form):  # в form главн. форма из get_context_data
        context = self.get_context_data()  # забраем контекст
        orderitems = context['orderitems']  # из него orderitems

        # with transaction.atomic():
        self.object = form.save()
        if orderitems.is_valid():
            orderitems.instance = self.object
            orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


# Шаблон удаления должен иметь имя вида «<имя класса>_confirm_delete.html»
class OrderItemsDelete(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('order:orders_list')

    def get_queryset(self):
        return Order.objects.filter(buyer=self.request.user)


# Шаблон по умолчанию для класса «DetailView»
# должен иметь имя вида  «<имя класса>_detail.html»
class OrderRead(LoginRequiredMixin, DetailView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(buyer=self.request.user)

# обновление статуса заказа при совершении покупки

def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SEND_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:orders_list'))

orderapp/templates/orderapp/base.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block order %}
{% endblock order %}

{% block feature %}
{% endblock feature %}

{% block subscribe %}
{% endblock subscribe %}

orderapp/templates/orderapp/order_confirm_delete.html
{% extends 'orderapp/base.html' %}
{% load static %}

{% block order %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'orderapp/includes/inc_order_summary.html' %}
        <form action="{% url 'orderapp:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'orderapp:orders_list' %}">отмена</a>
        </button>
    </div>

{% endblock order %}

orderapp/templates/orderapp/order_detail.html
{% extends 'orderapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block order %}
    {% include 'orderapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        {% for item in object.orderitems.select_related %}
            <div class="basket_record">
                <img src="{{ item.product.image|foto_product }}"
                     alt="{{ item.product.short_desc }}">
                <span class="category_name">
{{ item.product.category.name }}
</span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">
{{ item.product.price }}&nbspруб
</span>
                <span class="product_quantitiy">
x {{ item.quantity }} шт.
</span>
                <span class="product_cost">
= {{ item.get_product_cost }}&nbspруб
</span>
            </div>
        {% endfor %}
    </div>
    {% include 'orderapp/includes/inc_order_actions.html' %}
{% endblock order %}

orderapp/templates/orderapp/order_form.html
{% extends 'orderapp/base.html' %}
{% load static %}

{% block order %}
    {% include 'orderapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' %} order
                            formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' %} order
                            formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-success
                btn-round form-control last">
                сохранить
            </button>
            {% include 'orderapp/includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock order %}

orderapp/templates/orderapp/order_list.html
{% extends 'orderapp/base.html' %}
{% load static %}

{% block order %}
    <div class="h2 text-center head">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.first_name }}
        {% else %}
            {{ user.username }}
        {% endif %}
    </div>
    <table class="table orders_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a href="{% url 'orderapp:order_read' item.pk %}">
                            посмотреть
                        </a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'orderapp:order_update' item.pk %}">
                                редактировать
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'orderapp:order_delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'main' %}">
            на главную
        </a>

    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'orderapp:order_create' %}">
            новый
        </a>
    </button>

    {#    <section class="checkout_area section_padding">#}
    {#        <div class="container">#}
    {#            <div class="billing_details">#}
    {#                <div class="row">#}
    {#                    <div class="col-lg-8">#}
    {#                        <h3>Billing Details</h3>#}
    {#                        <form class="row contact_form" action="#" method="post" novalidate="novalidate">#}
    {#                            <div class="col-md-6 form-group p_star">#}
    {#                                <input type="text" class="form-control" id="first" name="name"/>#}
    {#                                <span class="placeholder" data-placeholder="First name"></span>#}
    {#                            </div>#}
    {#                            <div class="col-md-6 form-group p_star">#}
    {#                                <input type="text" class="form-control" id="last" name="name"/>#}
    {#                                <span class="placeholder" data-placeholder="Last name"></span>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group">#}
    {#                                <input type="text" class="form-control" id="company" name="company"#}
    {#                                       placeholder="Company name"/>#}
    {#                            </div>#}
    {#                            <div class="col-md-6 form-group p_star">#}
    {#                                <input type="text" class="form-control" id="number" name="number"/>#}
    {#                                <span class="placeholder" data-placeholder="Phone number"></span>#}
    {#                            </div>#}
    {#                            <div class="col-md-6 form-group p_star">#}
    {#                                <input type="text" class="form-control" id="email" name="compemailany"/>#}
    {#                                <span class="placeholder" data-placeholder="Email Address"></span>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group p_star">#}
    {#                                <select class="country_select">#}
    {#                                    <option value="1">Country</option>#}
    {#                                    <option value="2">Country</option>#}
    {#                                    <option value="4">Country</option>#}
    {#                                </select>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group p_star">#}
    {#                                <input type="text" class="form-control" id="add1" name="add1"/>#}
    {#                                <span class="placeholder" data-placeholder="Address line 01"></span>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group p_star">#}
    {#                                <input type="text" class="form-control" id="add2" name="add2"/>#}
    {#                                <span class="placeholder" data-placeholder="Address line 02"></span>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group p_star">#}
    {#                                <input type="text" class="form-control" id="city" name="city"/>#}
    {#                                <span class="placeholder" data-placeholder="Town/City"></span>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group p_star">#}
    {#                                <select class="country_select">#}
    {#                                    <option value="1">District</option>#}
    {#                                    <option value="2">District</option>#}
    {#                                    <option value="4">District</option>#}
    {#                                </select>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group">#}
    {#                                <input type="text" class="form-control" id="zip" name="zip" placeholder="Postcode/ZIP"/>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group">#}
    {#                                <div class="creat_account">#}
    {#                                    <input type="checkbox" id="f-option2" name="selector"/>#}
    {#                                    <label for="f-option2">Create an account?</label>#}
    {#                                </div>#}
    {#                            </div>#}
    {#                            <div class="col-md-12 form-group">#}
    {#                                <div class="creat_account">#}
    {#                                    <h3>Shipping Details</h3>#}
    {#                                    <input type="checkbox" id="f-option3" name="selector"/>#}
    {#                                    <label for="f-option3">Ship to a different address?</label>#}
    {#                                </div>#}
    {#                                <textarea class="form-control" name="message" id="message" rows="1"#}
    {#                                          placeholder="Order Notes"></textarea>#}
    {#                            </div>#}
    {#                        </form>#}
    {#                    </div>#}
    {#                    <div class="col-lg-4">#}
    {#                        <div class="order_box">#}
    {#                            <h2>Your Order</h2>#}
    {#                            <ul class="list">#}
    {#                                <li>#}
    {#                                    <a href="#">Product#}
    {#                                        <span>Total</span>#}
    {#                                    </a>#}
    {#                                </li>#}
    {#                                <li>#}
    {#                                    <a href="#">Fresh Blackberry#}
    {#                                        <span class="middle">x 02</span>#}
    {#                                        <span class="last">$720.00</span>#}
    {#                                    </a>#}
    {#                                </li>#}
    {#                                <li>#}
    {#                                    <a href="#">Fresh Tomatoes#}
    {#                                        <span class="middle">x 02</span>#}
    {#                                        <span class="last">$720.00</span>#}
    {#                                    </a>#}
    {#                                </li>#}
    {#                                <li>#}
    {#                                    <a href="#">Fresh Brocoli#}
    {#                                        <span class="middle">x 02</span>#}
    {#                                        <span class="last">$720.00</span>#}
    {#                                    </a>#}
    {#                                </li>#}
    {#                            </ul>#}
    {#                            <ul class="list list_2">#}
    {#                                <li>#}
    {#                                    <a href="#">Subtotal#}
    {#                                        <span>$2160.00</span>#}
    {#                                    </a>#}
    {#                                </li>#}
    {#                                <li>#}
    {#                                    <a href="#">Shipping#}
    {#                                        <span>Flat rate: $50.00</span>#}
    {#                                    </a>#}
    {#                                </li>#}
    {#                                <li>#}
    {#                                    <a href="#">Total#}
    {#                                        <span>$2210.00</span>#}
    {#                                    </a>#}
    {#                                </li>#}
    {#                            </ul>#}
    {#                            <div class="payment_item">#}
    {#                                <div class="radion_btn">#}
    {#                                    <input type="radio" id="f-option5" name="selector"/>#}
    {#                                    <label for="f-option5">Check payments</label>#}
    {#                                    <div class="check"></div>#}
    {#                                </div>#}
    {#                                <p>#}
    {#                                    Please send a check to Store Name, Store Street, Store Town,#}
    {#                                    Store State / County, Store Postcode.#}
    {#                                </p>#}
    {#                            </div>#}
    {#                            <div class="payment_item active">#}
    {#                                <div class="radion_btn">#}
    {#                                    <input type="radio" id="f-option6" name="selector"/>#}
    {#                                    <label for="f-option6">Paypal </label>#}
    {#                                    <img src="img/product/single-product/card.jpg" alt=""/>#}
    {#                                    <div class="check"></div>#}
    {#                                </div>#}
    {#                                <p>#}
    {#                                    Please send a check to Store Name, Store Street, Store Town,#}
    {#                                    Store State / County, Store Postcode.#}
    {#                                </p>#}
    {#                            </div>#}
    {#                            <div class="creat_account">#}
    {#                                <input type="checkbox" id="f-option4" name="selector"/>#}
    {#                                <label for="f-option4">I’ve read and accept the </label>#}
    {#                                <a href="#">terms & conditions*</a>#}
    {#                            </div>#}
    {#                            <a class="btn_3" href="#">Proceed to Paypal</a>#}
    {#                        </div>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </section>#}
{% endblock order %}